# **Analise de Dados via Pandas**
---

Uma empresa contratou uma equipe (que são vocês) para analisar uma planilha de cancelamento dos planos dessa empresa. O objetivo da equipe é analisar a planilha para verificar o porque do cancelamento e o que pode ser feito a respeito para diminuir o número de cancelamentos.


A primeira coisa a ser feira e ler a planilha usando o pandas.

In [17]:
import pandas as pd 

tabela = pd.read_csv("datasets/cancelamentos.csv")
display(tabela)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

Vamos retirar a clouna **CustomerID** da consulta , pois ela noa e interessate para a analise.

Vamos analisar se essa tabela possui alguma valor nulo, e para isso vamos verificar o numero de linha da tabela.

In [18]:
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 881666 entries, 0 to 881665
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CustomerID              881664 non-null  float64
 1   idade                   881664 non-null  float64
 2   sexo                    881664 non-null  object
 3   tempo_como_cliente      881663 non-null  float64
 4   frequencia_uso          881663 non-null  float64
 5   ligacoes_callcenter     881664 non-null  float64
 6   dias_atraso             881664 non-null  float64
 7   assinatura              881661 non-null  object
 8   duracao_contrato        881663 non-null  object
 9   total_gasto             881664 non-null  float64
 10  meses_ultima_interacao  881664 non-null  float64
 11  cancelou                881664 non-null  float64
dtypes: float64(9), object(3)
memory usage: 80.7+ MB

None

Repare que o numero total de entradas nao bate com numero de valores nao nulas de cada uma das coluna, e nem o numero de linhas com valores nao-nulas e o o mesmo para cada uma das colunas.

Precisaremos eliminar os valores nulos da tabela.

In [19]:
# eliminando os valores nulos
tabela = tabela.dropna()

display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
Index: 881659 entries, 0 to 881665
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CustomerID              881659 non-null  float64
 1   idade                   881659 non-null  float64
 2   sexo                    881659 non-null  object
 3   tempo_como_cliente      881659 non-null  float64
 4   frequencia_uso          881659 non-null  float64
 5   ligacoes_callcenter     881659 non-null  float64
 6   dias_atraso             881659 non-null  float64
 7   assinatura              881659 non-null  object
 8   duracao_contrato        881659 non-null  object
 9   total_gasto             881659 non-null  float64
 10  meses_ultima_interacao  881659 non-null  float64
 11  cancelou                881659 non-null  float64
dtypes: float64(9), object(3)
memory usage: 87.4+ MB

None

## Analise de dados
----


Agora que fizemos o tratamento de dados, a analise dde dados proprieamente dita vai cimerçat. Primeiramente, vamos verificar a qualidade de clientes que cancelaram o contrato versis a quantidade de clientes que ainda  estao com o contrato virgente.

In [20]:
# retorna o total de cancelamnetos e o toltal de contratos ainda vigentes
display(tabela['cancelou'].value_counts())

cancelou
1.0    499993
0.0    381666
Name: count, dtype: int64

A linha com o valor 1.0 representa os cancelamentos, equanto a linha com o valor 0.0 representa os contratos ainda virgentes.

Podemos pereceber que o numero de cancelamentos e maior do que o numero de contratos ainda viregentes,  oque significa que a empresa perdeu a maioria de seus clientes .A pergunta ahora e: por quê ?

Antes de respodemso a essa pergunta, vamos veridficar a porcetagem de cada um dos valores.

In [21]:
display(tabela['cancelou'].value_counts(normalize=True).map("{:.2%}".format))

cancelou
1.0    56.71%
0.0    43.29%
Name: proportion, dtype: object

## Motando o perfil de cancelamento da empresa 
----

Vamos tentar descobrir qaul o perfil de cancelameto da empresa, e para isso camos analisar o s tipos de contratos existentes  na empresas na empresa com base no periodo de cada contrato.

In [16]:
display(tabela['duracao_contrato'].value_counts())
display(tabela['duracao_contrato'].value_counts(normalize=True).map("{:.2%}".format))

duracao_contrato
Annual       354395
Quarterly    353059
Monthly      174205
Name: count, dtype: int64

duracao_contrato
Annual       40.20%
Quarterly    40.04%
Monthly      19.76%
Name: proportion, dtype: object

Vamos agrupar as informações da coluna **dração_contract** e fazer  a media das informações .

In [27]:
display(tabela.groupby('duracao_contrato').mean(numeric_only=True))

,CustomerID,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
duracao_contrato,,,,,,,,,
Annual,248548.543879,38.842165,31.446186,15.880213,3.263401,12.465156,651.697738,14.236107,0.460760
Monthly,130598.184731,41.552407,30.538555,15.499274,4.985649,15.007267,550.616435,15.478012,1.000000
Quarterly,248940.469177,38.830938,31.419916,15.886662,3.265245,12.460863,651.427783,14.234544,0.460255

Repare que **EXATOS 100%**  dos cleintes que optaram pelo contrato mensal cancelaram o contrato logo, sabemos agora que esse ripo de contrato e problematico e portanto  precisamos  elima-lo
e exibir um relaroiro sem o contrasos messais.

In [31]:
tabela = tabela[tabela['duracao_contrato'] != 'monthly']

display(tabela)
display(tabela['cancelou'].value_counts())
display(tabela['cancelou'].value_counts(normalize=True).map("{:.2%}".format))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

cancelou
1.0    499993
0.0    381666
Name: count, dtype: int64

cancelou
1.0    56.71%
0.0    43.29%
Name: proportion, dtype: object

A proporção de cancelamentos agora caiu para 46,05%. porem esse numero ainda e muito alto. Então precisamos ir mais a fundo  e ver onde epodemos eleiminar mais para dimininuir mais inda essa taxa.

## Graficos
----

Uma das melhoresformas de se analisar dados e atraves de graficos, pois fica muito mais facil visuzaluzar os dados o obter informações.

Para conseguirmos fazer isso, precisamos instalar um bliblioteca grafica para analaisar cada uma das colunas. Vamos a blibloteca platly , intalando-a atraves do comando pip install plotly no terminal.

In [ ]:
import plotly.express as px

for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color='cancelou', width=600)
    grafico.show()

Podemos verificar quea as taxas de cancelammentos sao de 100% para os clientes que:


1. Precisamosliigar para o call centert por mais de 5 vezes
2. Atrsaram o pagamento da assinatura por mais  de 20 dias.

Logo, vamos eleiminar da colsta todos os clientes que ligaram mais de 5 vezes para o call center, e tambem o pagamento por 10 dias ou mais .

In [36]:
tabela = tabela[tabela["ligacoes_callcenter"] < 5]
tabela = tabela[tabela["dias_atraso"] <= 20]


display(tabela)
display(tabela['cancelou'].value_counts())
display(tabela['cancelou'].value_counts(normalize=True).map("{:.2%}".format))

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
6,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.00,24.0,1.0
7,10.0,55.0,Female,37.0,8.0,4.0,15.0,Premium,Annual,445.00,30.0,1.0
9,12.0,64.0,Female,3.0,25.0,2.0,11.0,Standard,Quarterly,415.00,29.0,1.0
13,16.0,48.0,Female,35.0,25.0,1.0,13.0,Basic,Annual,518.00,17.0,1.0
19,22.0,42.0,Male,15.0,16.0,2.0,14.0,Premium,Quarterly,262.00,16.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881660,449994.0,45.0,Male,6.0,25.0,2.0,15.0,Basic,Annual,837.00,2.0,0.0
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

cancelou
0.0    360770
1.0    132787
Name: count, dtype: int64

cancelou
0.0    73.10%
1.0    26.90%
Name: proportion, dtype: object